name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths-ignore:
      - "**.md"
      - "renovate.json"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Setup git
        run: 'git config --global user.email "actions@github.com" && git config --global user.name "GitHub Actions"'
      - name: Download BuildTools
        run: mkdir -p ./build/ && curl -L -o ./build/BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
      - name: Setup Java JDK (Java 8)
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: temurin
      - name: Build Spigot 1.15.2
        run: cd build && java -jar BuildTools.jar --rev 1.15.2 && cd ..
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build Spigot 1.19.4
        run: cd build && java -jar BuildTools.jar --rev 1.19.4 && cd ..
      - name: Prepare gradle.properties
        run: |
          mkdir -p $HOME/.gradle
          echo "repoUsername=${{ secrets.REPO_USERNAME }}" >> $HOME/.gradle/gradle.properties
          echo "repoPassword=${{ secrets.REPO_PASSWORD }}" >> $HOME/.gradle/gradle.properties
      - name: Deploy
        run: ./gradlew clean test publish
